from __future__ import annotations

import json
import os
from pathlib import Path
from typing import List

from src.common.models import Document


def load_jsonl_documents(path: str | Path) -> List[Document]:
    docs: List[Document] = []
    with Path(path).open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            docs.append(
                Document(
                    doc_id=item["doc_id"],
                    title=item.get("title", ""),
                    content=item.get("content", ""),
                    metadata={
                        "category": item.get("category", ""),
                        "source": item.get("source", ""),
                        "valid_until": item.get("valid_until", ""),
                    },
                )
            )
    return docs


def load_mineru_markdown_documents(path: str | Path) -> List[Document]:
    """
    Load Markdown files generated by MinerU pipeline.

    Expected input: a directory containing .md files (possibly nested).
    """
    base_path = Path(path)
    if not base_path.exists():
        raise FileNotFoundError(f"MinerU output path not found: {base_path}")

    markdown_files = sorted(base_path.glob("**/*.md"))
    docs: List[Document] = []
    for md_file in markdown_files:
        text = md_file.read_text(encoding="utf-8", errors="ignore").strip()
        if not text:
            continue
        doc_id = md_file.stem
        docs.append(
            Document(
                doc_id=doc_id,
                title=md_file.stem,
                content=text,
                metadata={
                    "category": "mineru_doc",
                    "source": "mineru",
                    "valid_until": "",
                    "file_path": str(md_file.as_posix()),
                },
            )
        )
    return docs


def load_mineru_langchain_documents(
    input_dir: str | Path,
    *,
    mode: str = "flash",
    token: str | None = None,
    split_pages: bool = True,
    language: str = "ch",
    timeout: int = 1200,
) -> List[Document]:
    """
    Load documents via langchain-mineru cloud API (flash/precision).
    """
    try:
        from langchain_mineru import MinerULoader
    except ImportError as exc:
        raise ImportError(
            "langchain-mineru is not installed. Please run: pip install langchain-mineru"
        ) from exc

    input_path = Path(input_dir)
    if not input_path.exists():
        raise FileNotFoundError(f"MinerU input dir not found: {input_path}")

    # Support PDF and common office/image documents supported by langchain-mineru.
    patterns = ["**/*.pdf", "**/*.docx", "**/*.pptx", "**/*.xlsx", "**/*.xls", "**/*.png", "**/*.jpg", "**/*.jpeg"]
    sources: List[str] = []
    for pattern in patterns:
        sources.extend([str(p) for p in sorted(input_path.glob(pattern))])
    if not sources:
        return []

    mode_norm = (mode or "flash").strip().lower()
    token_eff = (token or "").strip() or os.environ.get("MINERU_API_TOKEN", "").strip()
    if mode_norm == "precision" and not token_eff:
        raise ValueError(
            "mineru_mode=precision requires a MinerU API token. "
            "Set environment variable MINERU_API_TOKEN or ingestion.mineru_token in settings.yaml."
        )

    loader_kwargs = {
        "mode": mode_norm,
        "language": language,
        "split_pages": split_pages,
        "timeout": timeout,
    }
    if mode_norm == "precision":
        loader_kwargs["token"] = token_eff

    lc_docs = []
    failed_sources: List[str] = []
    for src in sources:
        try:
            loader = MinerULoader(source=src, **loader_kwargs)
            docs = loader.load()
            lc_docs.extend(docs)
        except Exception:
            # Some files may return empty markdown in flash mode. Skip and continue.
            failed_sources.append(src)

    if not lc_docs and failed_sources:
        raise ValueError(
            "MinerU loader failed for all sources. "
            f"sample_failed_source={failed_sources[0]}"
        )
    docs: List[Document] = []
    for i, doc in enumerate(lc_docs):
        if not doc.page_content or not doc.page_content.strip():
            continue
        metadata = {k: str(v) for k, v in doc.metadata.items()}
        source = metadata.get("source", "")
        page = metadata.get("page")
        file_stem = Path(source).stem if source else f"doc_{i}"
        suffix = f"_p{page}" if page else f"_{i}"
        docs.append(
            Document(
                doc_id=f"{file_stem}{suffix}",
                title=metadata.get("filename", file_stem),
                content=doc.page_content.strip(),
                metadata={
                    "category": "mineru_doc",
                    "source": source or "mineru_langchain",
                    "valid_until": "",
                    "loader": "langchain-mineru",
                    "mode": metadata.get("mode", mode_norm),
                    "page": str(page) if page is not None else "",
                },
            )
        )
    return docs


def load_documents(
    source_type: str,
    kb_file: str | Path,
    mineru_output_dir: str | Path | None = None,
    mineru_input_dir: str | Path | None = None,
    mineru_mode: str = "flash",
    mineru_token: str | None = None,
    mineru_split_pages: bool = True,
    mineru_language: str = "ch",
    mineru_timeout: int = 1200,
) -> List[Document]:
    if source_type == "jsonl":
        return load_jsonl_documents(kb_file)
    if source_type == "mineru_markdown":
        if mineru_output_dir is None:
            raise ValueError("mineru_output_dir is required when source_type='mineru_markdown'")
        return load_mineru_markdown_documents(mineru_output_dir)
    if source_type == "mineru_langchain":
        if mineru_input_dir is None:
            raise ValueError("mineru_input_dir is required when source_type='mineru_langchain'")
        return load_mineru_langchain_documents(
            mineru_input_dir,
            mode=mineru_mode,
            token=mineru_token,
            split_pages=mineru_split_pages,
            language=mineru_language,
            timeout=mineru_timeout,
        )
    raise ValueError(f"Unsupported source_type: {source_type}")
